# Generated by Django 4.0.2 on 2022-11-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_alter_post_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='college',
            field=models.CharField(choices=[('인문과학계열', '인문과학계열(HUMANITY)'), ('사회과학계열', '사회과학계열(SOCIETY)'), ('자연과학계열', '자연과학계열(SCIENCE)'), ('공학계열', '공학계열(ENGINNERING)'), ('자유게시판', '자유게시판(FREE)')], default='인문과학계열', max_length=10),
        ),
    ]
