# Generated by Django 4.0.5 on 2022-11-21 16:52

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('studentID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('college', models.CharField(choices=[('인문과학계열', '인문과학계열(HUMANITY)'), ('사회과학계열', '사회과학계열(SOCIETY)'), ('자연과학계열', '자연과학계열(SCIENCE)'), ('공학계열', '공학계열(ENGINNERING)')], max_length=10)),
                ('accepted', models.BooleanField(default=False)),
                ('gpa', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.5)])),
                ('gpa_all', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.5)])),
                ('identifier_image', models.ImageField(blank=True, default=None, upload_to='')),
                ('major', models.CharField(choices=[('유학동양학과', '유학동양학과'), ('국어국문학과', '국어국문학과'), ('영어영문학과', '영어영문학과'), ('프랑스어문학과', '프랑스어문학과'), ('러시아어문학과', '러시아어문학과'), ('중어중문학과', '중어중문학과'), ('독어독문학과', '독어독문학과'), ('한문학과', '한문학과'), ('사학과', '사학과'), ('철학과', '철학과'), ('문헌정보학과', '문헌정보학과'), ('행정학과', '행정학과'), ('정치외교학과', '정치외교학과'), ('미디어커뮤니케이션학과', '미디어커뮤니케이션학과'), ('사회학과', '사회학과'), ('사회복지학과', '사회복지학과'), ('심리학과', '심리학과'), ('소비자학과', '소비자학과'), ('아동&청소년학과', '아동&청소년학과'), ('경제학과', '경제학과'), ('통계학과', '통계학과'), ('생명과학과', '생명과학과'), ('수학과', '수학과'), ('물리학과', '물리학과'), ('화학과', '화학과'), ('식품생명공학과', '식품생명공학과'), ('바이오메카트로닉스학과', '바이오메카트로닉스학과'), ('융합생명공학과', '융합생명공학과'), ('화학공부/고분자시스템공학부', '화학공부/고분자시스템공학부'), ('신소재공학부', '신소재공학부'), ('기계공학부', '기계공학부'), ('건설환경공학부', '건설환경공학부'), ('시스템경영공학과', '시스템경영공학과'), ('나노공학과', '나노공학과'), ('데이터사이언스융합전공', '데이터사이언스융합전공'), ('인공지능융합전공', '인공지능융합전공'), ('컬처앤테크놀로지융합전공', '컬처앤테크놀로지융합전공')], default='데이터사이언스융합전공', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lecture_type', models.CharField(choices=[('의사소통', '의사소통(COMMUNICATE)'), ('창의', '창의(CREATIVE)'), ('글로벌', '글로벌(GLOBAL)'), ('기초인문사회/BSM', '기초인문사회/BSM'), ('성균인성/리더쉽(LEADERSHIP)', '성균인성/리더쉽(LEADERSHIP)'), ('고전명저', '고전명저(BOOK)'), ('DS기반', 'DS기반(DS)'), ('핵심균형', '핵심균형(BALANCE)'), ('전공일반/전공핵심', '전공일반/전공핵심(MAJOR)'), ('일반선택', '일반선택(ETC)')], default='일반선택', max_length=200)),
                ('point', models.IntegerField(default=1)),
                ('score', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('P', 'P')], default='A+', max_length=200)),
                ('writer', models.ForeignKey(db_column='studentID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
